// LOCALHOST ### Get all contacts GET http://localhost:8080/contacts

### Get contact by id GET http://localhost:8080/contacts/62a6b52b729308c4ccae9275

### Create contact POST http://localhost:8080/contacts HTTP/1.1 content-type: application/json


### PUT contact PUT http://localhost:8080/contacts/62a6b52b729308c4ccae9275 HTTP/1.1 content-type: application/json

{
"firstName":"Sarah", "lastName":"Birch", "email":"test@gmail.com", "favoriteColor":"Green", "birthday":"12/12/20"
} ### DELETE contact DELETE http://localhost:8080/contacts/62a6b52b729308c4ccae9275 HTTP/1.1

// PRODUCTION Deploy ### 


Get all contacts GET https://cse341nodecabrera.herokuapp.com/contacts

### Get contact by id GET https://cse341nodecabrera.herokuapp.com/contacts/62a6b52b729308c4ccae9275

### Create contact POST https://cse341nodecabrera.herokuapp.com/contacts HTTP/1.1 content-type: application/json



### PUT contact PUT https://cse341nodecabrera.herokuapp.com/contacts/62a6b52b729308c4ccae9275 HTTP/1.1 content-type: application/json

{
"firstName":"Sarah", "lastName":"Birch", "email":"sarahB@gmail.com", "favoriteColor":"Yellow", "birthday":"06/12/20"
}

### DELETE contact DELETE https://cse341nodecabrera.herokuapp.com/contacts/62a6b52b729308c4ccae9275 HTTP/1.1



{

"firstName": "mike",

"lastName": "mike",

"email": "hi@helle.com",

"favoriteColor" : "red",

"birthday": "sunday"

}